"""
Report Generator — Produces structured Markdown and PDF daily reports
using NLP insights + RAG-generated summaries.
"""

from __future__ import annotations
from datetime import datetime
from typing import Dict, Any, List

from src.rag.pipeline import RAGPipeline


class ReportGenerator:

    def __init__(self, rag_pipeline: RAGPipeline, nlp_results: Dict[str, Any]):
        self.rag = rag_pipeline
        self.nlp = nlp_results

    def generate(
        self,
        project_name: str,
        author: str,
        date: str,
        notes: str = "",
        filenames: List[str] | None = None
    ) -> Dict[str, str]:
        """Generate a full project intelligence report in Markdown."""

        # Get AI-generated sections via RAG
        ai_summary = self.rag.summarize_all()
        risks = self.rag.query("What are the main risks, blockers, or challenges mentioned?")["answer"]
        progress = self.rag.query("What progress, milestones, or achievements are mentioned?")["answer"]
        actions = self.rag.query("What are the next steps, action items, or recommendations?")["answer"]

        kw_str = ", ".join([f"**{kw}** ({score:.2f})" for kw, score in self.nlp["keywords"][:8]])
        phrases_str = "\n".join([f"- {p}" for p in self.nlp["key_phrases"][:8]])
        sentiment = self.nlp["sentiment"]
        breakdown = self.nlp["sentiment_breakdown"]
        files_str = "\n".join([f"- `{f}`" for f in (filenames or [])]) or "- *(not specified)*"

        md = f"""# 📊 Project Intelligence Report
**Project:** {project_name}
**Author:** {author}
**Date:** {date}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## 📁 Source Documents
{files_str}

---

## 🧠 Executive Summary
{ai_summary}

---

## 📈 Progress & Milestones
{progress}

---

## ⚠️ Risks & Blockers
{risks}

---

## ✅ Next Steps & Action Items
{actions}

---

## 📊 Document Analytics

| Metric | Value |
|--------|-------|
| Total Words | {self.nlp['word_count']:,} |
| Unique Terms | {self.nlp['unique_terms']:,} |
| Sentences | {self.nlp['sentence_count']:,} |
| Readability | {self.nlp['readability_grade']} |
| Overall Sentiment | {sentiment['label']} ({sentiment['score']:.0%} confidence) |
| Positive Tone | {breakdown['positive']:.0%} of sentences |
| Negative Tone | {breakdown['negative']:.0%} of sentences |
| Neutral Tone | {breakdown['neutral']:.0%} of sentences |

---

## 🔑 Key Topics & Keywords
{kw_str}

## 📌 Key Phrases Identified
{phrases_str}

---

## 📋 Document Summary
{self.nlp['summary']}

---

{"## 📝 Additional Notes" + chr(10) + notes + chr(10) + chr(10) + "---" + chr(10) if notes.strip() else ""}

*Report generated by AI Project Intelligence System · Powered by Groq + sentence-transformers*
"""
        return {"markdown": md}

    def to_pdf(self, markdown_text: str) -> bytes:
        """Convert Markdown report to PDF bytes using fpdf2."""
        try:
            from fpdf import FPDF
        except ImportError:
            raise ImportError("Install fpdf2: pip install fpdf2")

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_font("Helvetica", size=11)

        for line in markdown_text.split("\n"):
            line = line.strip()
            if not line:
                pdf.ln(3)
                continue
            if line.startswith("# "):
                pdf.set_font("Helvetica", "B", 16)
                pdf.cell(0, 10, line[2:], ln=True)
                pdf.set_font("Helvetica", size=11)
            elif line.startswith("## "):
                pdf.set_font("Helvetica", "B", 13)
                pdf.cell(0, 8, line[3:], ln=True)
                pdf.set_font("Helvetica", size=11)
            elif line.startswith("---"):
                pdf.set_draw_color(200, 200, 200)
                pdf.line(10, pdf.get_y(), 200, pdf.get_y())
                pdf.ln(2)
            elif line.startswith("**") or line.startswith("- "):
                clean = line.replace("**", "").replace("`", "")
                pdf.set_font("Helvetica", size=10)
                pdf.multi_cell(0, 6, clean)
                pdf.set_font("Helvetica", size=11)
            else:
                clean = line.replace("**", "").replace("`", "").replace("*", "")
                pdf.multi_cell(0, 6, clean)

        return pdf.output()
